### ISSUE TITLE
Fixing structure of the code to more OOP

### ISSUE THREAD

**Issue by GrzegorzKarczewski** [GrzegorzKarczewski/BMI-Calculator#5]
Right now as i see it and look on object oriented programming videos my code looks messy. 
But as of today, i lack knowledge and experience to fix it.
a lot of code can be moved probably to seperate classes

**Comment by pazurkota** [comment]
Well, as i looked on this code it's not very bad
It's a little bit messy and not that "pretty"

But remember about the "single responsibility principle" rule (one class for one purporse)
It's a first rule of SOLID rules and in my opinion, one of the most important rule in OOP

**Comment by GrzegorzKarczewski** [comment]
Thanks. I'm still learning and i've already started to rewrite the program using proper "by hand-writen" XAML and using MVVM architecture. It's a totaly new thing for me, so it's gonna take some time. Thanks for the important tip!

**Comment by pazurkota** [comment]
No problem mate!

If you have a free time, you can try Git Flow:
Basicly, you have 2 branches:
- master/main (for stabile build of your app)
- develop (for experimental features)

If you implementing a feature, you are creating `feature/feature` branch.

### Here is some example:
You are creating an app to check weather, and you want to add forecast feature (for example)
So you are creating `feature/forecast` branch and do your job on this branch
After you finish, you can merge directly to `develop` branch or if you are work in team, create a pull request
I think it's a very good idea to get similar with Git Flow, because it makes the job more arranged

**Comment by pazurkota** [comment]
Im currently working on my fork to fix this issue
I will open a pull request soon

**Comment by GrzegorzKarczewski** [comment]
Closing thanks to #7
